sudo: false

language: ruby

cache: bundler

rvm:
  # - 2.1
  - 2.2

notifications:
  email: false
  irc:
    channels: "irc.freenode.org#travisstaging"
    template: "[STAGING] %{repository} (%{commit}) %{build_url} : %{message} - AM I RIGHT?"
  # flowdock: e533e9b0984a1cc7650579ab7aaab158
  # hipchat: "a21b28b2863acbee3ccb17da36a173@Travis CI"
  webhooks:
    urls: http://requestb.in/x6g8i2x6
    on_start: always
    on_finish: always

script:
  # - sleep 120 # test custom log_silence timeout
  - date
  - travis_retry ./error_out
  - echo "NEXT SCRIPT!!"
  - export EXPORTED_DURING_SCRIPT="exported during script, works with travis_cmd still"
  - echo $EXPORTED_DURING_SCRIPT
  - echo $(echo "$EXPORTED_DURING_SCRIPT, even with an extra subshell")
  - echo $(echo "redirecting stdout" > ./foo && cat ./foo) > ./bar && cat ./bar

before_script:
  - "echo 'Before script!!'"
  - "sudo service postgresql restart"

after_script:
  - "echo 'After script'"

after_success:
  - "echo 'After success'"

after_failure:
  - "echo 'After failure'"

after_test:
  - "echo 'Yupi'"
  - "echo 'Splendid'"
  - printenv

env:
  global:
    - "GLOBAL_VAR=foo"
