os:
  - osx
  - linux

setup: echo "foo"

before_install:
  - test $TRAVIS_OS_NAME = "osx" && brew install nvm && source $(brew --prefix nvm)/nvm.sh
  - nvm install 0.10
  - node --version
  - npm --version
  - nvm --version
  

script: printenv
